import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className=" max-w-5xl mx-auto">{children}</div>
        <div className=" max-w-6xl mx-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
